public class Human {
    public String Name;
    public Integer Age;
    
    public Human(){
      this.Age = 0;
    }
        
    public void setName(String Name){
        this.Name = Name;
    } 
    
    public void setAge(String Name){
        this.Age = Age;
    } 
    
    public void Crawl(){
        System.debug('Crawl');
    } 
    
    public void Walk(){
        System.debug('Walk');
    } 
    
    public void Hike(){
        System.debug('Hike');
    } 
}